<?php
/* SISTEMA DESENVOLVIDO POR FRANCO VIEIRA MORALES  - INDAIATUBA 07NOV22
   SISTEMA DESARROLLADO  POR FRANCO VIEIRA MORALES - INDAIATUBA 07NOV22
   SYSTEM DEVELOPED BY FRANCO VIEIRA MORALES       - INDAIATUBA 07NOV22

   
   ULTMA ALTERAÇÃO - FRANCO VIEIRA MORALES - INDAIATUBA 07NOV22 - RES000101/13BR  */



 // ###  ROTINA PARA CARREGAR EQUIPAMENTO QUE FOI FILTRADO NA ESCOLHA DA CAIXA DE SELEÇÃO APLICADA ### //
require 'inc/conexao.php';

$equipamento = $_GET['equipamento'];

$sql = mysqli_query($con,"SELECT ITEM_COD_ITEM FROM t0005 WHERE ITEM_DESC_ITEM = '$equipamento'");

while($obj = mysqli_fetch_array($sql))
{
    $codigo = $obj['ITEM_COD_ITEM'];
}

print $codigo;

?>